#!/usr/bin/env bash

. /etc/videk/conf

IFCONF=${if:=wlan0}
HOSTCONF=${host:=sna-lgtc}

while true; do
    # set IP address as hostname
    IP=`ip addr show "$IFCONF" | grep -Po 'inet \K[\d.]+'`

    echo "Our IP is $IP"

    if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        HOSTNAME="$HOSTCONF-"${IP//[.]/-}

        echo $HOSTNAME > /etc/hostname

        sed -i -e '/127\.\0\.1\.1/d' /etc/hosts
        echo "127.0.1.1 $HOSTNAME ${HOSTNAME}.ijs.si" >> /etc/hosts

        /bin/hostname "$HOSTNAME"
        exit 0
    else
        echo "failed to set hostname"
    fi

    sleep 5
done
